os:
  - linux
language: java
jdk:
  - openjdk11
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script:
  - set -e
  - mvn clean install -Pcheckstyle #,itcases -PtestCoverage jacoco:report coveralls:report
